default['newrelic_mongodb_agent']['version'] = 'v2.4.4-3'
default['newrelic_mongodb_agent']['repository'] = 'https://github.com/MongoHQ/newrelic-mongodb-agent.git'
default['newrelic_mongodb_agent']['rvm_ruby'] = '2.1'
default['newrelic_mongodb_agent']['user'] = 'mongod'
default['newrelic_mongodb_agent']['install_root'] = '/opt/newrelic-mongodb-agent'
default['newrelic_mongodb_agent']['endpoint'] = 'localhost'